name: Commit Stage CI/CD Pipeline
on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/vasimvahabov/retail-product-demand-forecasting-system
  PRODUCT_VERSION: 1.0.0-${{ github.sha }}-${{ github.run_id }}

jobs:
  run-and-commit:
    name: Run Pipeline and Commit Artifacts
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Application
        run: |
          python src/main.py --stores 1 --all-phases

      - name: Commit Artifacts
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          git checkout --orphan ci/output
          git rm -rf .
          git add out/
          git add log/
          
          git commit -m "ci: persist generated artifacts [skip ci]"
          git push -u origin ci/output --force

  build-and-publish-image:
    runs-on: ubuntu-22.04
    name: Build and Publish Image
    needs: [ run-and-commit ]
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: build
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.PRODUCT_VERSION }} .

      - name: Login GitHub Contanier Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Image (Git Commit Hash)
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.PRODUCT_VERSION }}

      - name: Publish Image (latest)
        run: |
          docker tag \
                    ${{ env.IMAGE_NAME }}:${{ env.PRODUCT_VERSION }} \
                    ${{ env.IMAGE_NAME }}:latest
                docker push ${{ env.IMAGE_NAME }}:latest
